modLoader = "kotlinforforge"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId="ae2"
type="required"
versionRange="[19.2.16,)"
ordering="AFTER"
side="BOTH"
#[[dependencies.${mod_id}]]
#modId="ex-pattern-provider"
#type="required"
#versionRange="[2.2.22,)"
#ordering="AFTER"
#side="BOTH"
#[[dependencies.${mod_id}]]
#modId="advancedae"
#type="required"
#versionRange="[1.4.6,)"
#ordering="AFTER"
#side="BOTH"
#[[dependencies.${mod_id}]]
#modId="applied-flux"
#type="required"
#versionRange="[2.1.3,)"
#ordering="AFTER"
#side="BOTH"
#[[dependencies.${mod_id}]]
#modId="mega-cells"
#type="required"
#versionRange="[4.10.1,)"
#ordering="AFTER"
#side="BOTH"